### ISSUE TITLE
Be able to Replace Text with list of Images

### ISSUE THREAD

**Issue by fpdutra** [stutton/DocumentCreator#32]
I want to be able to set up a text, i. e., "{imagesFromBefore}" and be able to replace that text with the list of images.

**Comment by stutton** [comment]
Just to be sure I understand the request. You'd like to be able to mark a spot in the template file where the "List" (text and images) will be inserted so that the template can contain content _after_ the list. Correct?

**Comment by fpdutra** [comment]
Yes. I have three different places that I want to add three different groups of images. And after those three there is still some text.
